import { NextRequest, NextResponse } from "next/server";
import { requireAuth } from "@/lib/auth";
import { getActiveAi } from "@/lib/ai-config";
import OpenAI from "openai";
import Anthropic from "@anthropic-ai/sdk";

export const dynamic = "force-dynamic";

const SYSTEM_PROMPT =
  `You are the GroundControl terminal AI. Convert the user's natural-language intent into a single ` +
  `POSIX sh command that will run on a remote VPS whose default shell is BusyBox/sh (not bash).\n\n` +
  `RULES:\n` +
  `- Output ONLY valid JSON with keys "command" and "explanation".\n` +
  `- The command must be a single line (no newlines) unless you use ; or && for fallbacks.\n` +
  `- Use POSIX sh syntax only. NO bashisms: no [[ ]], no arrays, no source, no here-strings, no <().\n` +
  `- Prefer standard utilities: ps, awk, sed, grep, df, du, free, docker, systemctl, journalctl, ls, cat.\n` +
  `- When a user refers to "memory", use free -m or ps. For CPU, use ps or top. For disk, use df -h.\n` +
  `- If the intent is ambiguous, produce the safest, most common interpretation and explain it.\n` +
  `- NEVER output multiple commands or a script. ONE command only.`;

export async function POST(req: NextRequest) {
  try {
    await requireAuth(req);
    const { intent, cwd } = await req.json();
    if (!intent || typeof intent !== "string") {
      return NextResponse.json({ error: "intent required" }, { status: 400 });
    }

    const { provider, apiKey, model } = getActiveAi();
    if (!apiKey) {
      const label = provider === "anthropic" ? "ANTHROPIC_API_KEY" : "OPENAI_API_KEY";
      return NextResponse.json(
        { error: `${label} not configured. Add it in Settings → AI.` },
        { status: 503 }
      );
    }

    const userPrompt = `Current working directory: ${cwd || "/"}\nIntent: ${intent}\n\nReturn JSON: {"command": "...", "explanation": "..."}`;

    let result: { command: string; explanation: string };

    if (provider === "anthropic") {
      const anthropic = new Anthropic({ apiKey });
      const response = await anthropic.messages.create({
        model,
        max_tokens: 1024,
        system: SYSTEM_PROMPT,
        messages: [{ role: "user", content: userPrompt }],
      });
      const text = response.content
        .filter((b): b is Anthropic.TextBlock => b.type === "text")
        .map((b) => b.text)
        .join("");
      result = parseJsonResponse(text);
    } else {
      const openai = new OpenAI({ apiKey });
      const response = await openai.chat.completions.create({
        model,
        messages: [
          { role: "system", content: SYSTEM_PROMPT },
          { role: "user", content: userPrompt },
        ],
        temperature: 0.2,
      });
      const text = response.choices[0]?.message?.content || "";
      result = parseJsonResponse(text);
    }

    // Sanitize the command: remove newlines and trailing backticks.
    result.command = result.command.replace(/\n/g, " ").trim().replace(/`+$/g, "").trim();

    return NextResponse.json(result);
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}

function parseJsonResponse(text: string): { command: string; explanation: string } {
  try {
    // Try to extract JSON from a fenced code block if present.
    const fence = text.match(/```(?:json)?\s*([\s\S]*?)```/);
    const raw = fence ? fence[1] : text;
    const parsed = JSON.parse(raw);
    return {
      command: String(parsed.command || ""),
      explanation: String(parsed.explanation || ""),
    };
  } catch {
    // Fallback: look for command/explanation heuristically.
    const commandMatch = text.match(/"command"\s*:\s*"([^"]*)"/);
    const explanationMatch = text.match(/"explanation"\s*:\s*"([^"]*)"/);
    return {
      command: commandMatch ? commandMatch[1] : text.split("\n")[0] || "",
      explanation: explanationMatch ? explanationMatch[1] : "Generated by AI",
    };
  }
}
